name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: Display the files
      run: "ls -la"
      shell: bash
    - uses: actions/upload-artifact@v1
      with:
        name: build
        path: "public"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: build
    - name: Display the files
      run: "ls -la build"
      shell: bash
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "build"
        target: "/root/test/"
